# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.9'

services:
  sql-server-db:
    container_name: sql-server-sample-db
    image: mcr.microsoft.com/azure-sql-edge:latest
    ports:
      - 1433:1433
    volumes:
      - ~/mssql/data:/var/lib/mssqlql/data
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Monstarlab@123
      - MSSQL_PID=Developer
      - MSSQL_USER=sa
